package vista;

import controlador.DocIdentidadControlador;
import java.awt.HeadlessException;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import modelo.DocIdentidad;

/**
 *
 * @author mauro
 */
public class AgregarDocumentoIdentidadVista extends javax.swing.JPanel {

    /**
     * Creates new form Cliente
     */
    public AgregarDocumentoIdentidadVista() {
        initComponents();
        mostrarDocumentosEnTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        panelRound4 = new extra.PanelRound();
        jLabel3 = new javax.swing.JLabel();
        CI_CodigoDoc = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        CI_TipoDoc = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        CI_NumeroDocumento = new javax.swing.JTextField();
        panelRound5 = new extra.PanelRound();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla_Documentos = new javax.swing.JTable();
        Int_Guardar = new RSMaterialComponent.RSButtonMaterialIconDos();
        Int_Eliminar = new RSMaterialComponent.RSButtonMaterialIconDos();
        Int_Editar = new RSMaterialComponent.RSButtonMaterialIconDos();
        lnt_Buscar = new RSMaterialComponent.RSButtonMaterialIconDos();
        rSButtonMaterialIconDos5 = new RSMaterialComponent.RSButtonMaterialIconDos();

        setBackground(new java.awt.Color(239, 235, 233));

        jLabel1.setBackground(new java.awt.Color(58, 42, 83));
        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(61, 77, 33));
        jLabel1.setText("Registro de Documentos de Identidad");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(61, 77, 33));
        jLabel2.setText("Complete la informacion de los documentos de identidad");

        panelRound4.setBackground(new java.awt.Color(255, 255, 255));
        panelRound4.setRoundBottomLeft(75);
        panelRound4.setRoundBottomRight(75);
        panelRound4.setRoundTopLeft(75);
        panelRound4.setRoundTopRight(75);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Codigo Documento:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Tipo de Documento:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Numero de Documento:");

        javax.swing.GroupLayout panelRound4Layout = new javax.swing.GroupLayout(panelRound4);
        panelRound4.setLayout(panelRound4Layout);
        panelRound4Layout.setHorizontalGroup(
            panelRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound4Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(panelRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(CI_NumeroDocumento, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
                    .addComponent(jLabel5)
                    .addComponent(CI_TipoDoc, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(CI_CodigoDoc, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        panelRound4Layout.setVerticalGroup(
            panelRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound4Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CI_CodigoDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CI_TipoDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CI_NumeroDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        panelRound5.setBackground(new java.awt.Color(255, 255, 255));
        panelRound5.setRoundBottomLeft(75);
        panelRound5.setRoundBottomRight(75);
        panelRound5.setRoundTopLeft(75);
        panelRound5.setRoundTopRight(75);

        Tabla_Documentos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Tipo", "Numero Documento"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(Tabla_Documentos);

        javax.swing.GroupLayout panelRound5Layout = new javax.swing.GroupLayout(panelRound5);
        panelRound5.setLayout(panelRound5Layout);
        panelRound5Layout.setHorizontalGroup(
            panelRound5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound5Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 769, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        panelRound5Layout.setVerticalGroup(
            panelRound5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound5Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 624, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        Int_Guardar.setBackground(new java.awt.Color(61, 77, 33));
        Int_Guardar.setText("Guardar");
        Int_Guardar.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.SAVE);
        Int_Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Int_GuardarActionPerformed(evt);
            }
        });

        Int_Eliminar.setBackground(new java.awt.Color(61, 77, 33));
        Int_Eliminar.setText("Eliminar");
        Int_Eliminar.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.DELETE);
        Int_Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Int_EliminarActionPerformed(evt);
            }
        });

        Int_Editar.setBackground(new java.awt.Color(61, 77, 33));
        Int_Editar.setText("Editar");
        Int_Editar.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.EDIT);
        Int_Editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Int_EditarActionPerformed(evt);
            }
        });

        lnt_Buscar.setBackground(new java.awt.Color(61, 77, 33));
        lnt_Buscar.setText("Buscar");
        lnt_Buscar.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.SEARCH);
        lnt_Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lnt_BuscarActionPerformed(evt);
            }
        });

        rSButtonMaterialIconDos5.setBackground(new java.awt.Color(61, 77, 33));
        rSButtonMaterialIconDos5.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.GROUP_ADD);
        rSButtonMaterialIconDos5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMaterialIconDos5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelRound4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Int_Guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Int_Eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Int_Editar, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lnt_Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                        .addComponent(panelRound5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rSButtonMaterialIconDos5, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2))
                    .addComponent(rSButtonMaterialIconDos5, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelRound5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(panelRound4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Int_Guardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Int_Eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Int_Editar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lnt_Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(36, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void Int_GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Int_GuardarActionPerformed
        // TODO add your handling code here:
        try {
                // Crear el objeto con datos del formulario
                DocIdentidad documento = new DocIdentidad();
                documento.setIdDocIdentidad(CI_CodigoDoc.getText());
                documento.setTipoDocumento(CI_TipoDoc.getText());
                documento.setNumeroDocumento(CI_NumeroDocumento.getText());

                // Llamar al controlador
                DocIdentidadControlador controlador = new DocIdentidadControlador();
                controlador.registrarDocumento(documento);

                // Mostrar mensaje solo si NO hay error
                javax.swing.JOptionPane.showMessageDialog(this, "✅ Documento guardado correctamente");

                // Actualizar tabla
                mostrarDocumentosEnTabla();

                // Limpiar campos si deseas
                CI_CodigoDoc.setText("");
                CI_TipoDoc.setText("");
                CI_NumeroDocumento.setText("");

        } catch (Exception e) {
                // Mostrar mensaje en caso de error (por ejemplo, longitud excesiva)
                javax.swing.JOptionPane.showMessageDialog(this,
                    "Error al guardar el documento:\n" + e.getMessage(),
                    "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
    }//GEN-LAST:event_Int_GuardarActionPerformed

    private void Int_EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Int_EliminarActionPerformed
        // TODO add your handling code here:
        try {
            int filaSeleccionada = Tabla_Documentos.getSelectedRow();

            if (filaSeleccionada == -1) {
                javax.swing.JOptionPane.showMessageDialog(this,
                    "Por favor selecciona una fila para eliminar",
                    "Aviso", javax.swing.JOptionPane.WARNING_MESSAGE);
                return;
            }

            // Obtener el código del documento desde la tabla
            String idDoc = Tabla_Documentos.getValueAt(filaSeleccionada, 0).toString();

            // Confirmación
            int confirm = javax.swing.JOptionPane.showConfirmDialog(this,
                "¿Estás seguro de eliminar el documento con código: " + idDoc + "?",
                "Confirmar eliminación", javax.swing.JOptionPane.YES_NO_OPTION);

            if (confirm == javax.swing.JOptionPane.YES_OPTION) {
                DocIdentidadControlador controlador = new DocIdentidadControlador();
                controlador.eliminarDocumento(idDoc);
                mostrarDocumentosEnTabla(); // Actualizar tabla

                javax.swing.JOptionPane.showMessageDialog(this,
                    "Documento eliminado correctamente");
            }

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Error al eliminar el documento:\n" + e.getMessage(),
                "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_Int_EliminarActionPerformed

    private void Int_EditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Int_EditarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Int_EditarActionPerformed

    private void lnt_BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lnt_BuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lnt_BuscarActionPerformed

    private void rSButtonMaterialIconDos5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMaterialIconDos5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonMaterialIconDos5ActionPerformed

//MOSTRAR DOCUMENTOS EXISTENTES
    private void mostrarDocumentosEnTabla() {
    //Instanciamos con el controlador
        DocIdentidadControlador controlador = new DocIdentidadControlador(); 
        List<DocIdentidad> lista = controlador.obtenerDocumentos();
        
        DefaultTableModel modelo = (DefaultTableModel) Tabla_Documentos.getModel();
        modelo.setRowCount(0); // Limpiar tabla

        for (DocIdentidad doc : lista) {
            modelo.addRow(new Object[]{
                doc.getIdDocIdentidad(),
                doc.getTipoDocumento(),
                doc.getNumeroDocumento()
            });
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CI_CodigoDoc;
    private javax.swing.JTextField CI_NumeroDocumento;
    private javax.swing.JTextField CI_TipoDoc;
    private RSMaterialComponent.RSButtonMaterialIconDos Int_Editar;
    private RSMaterialComponent.RSButtonMaterialIconDos Int_Eliminar;
    private RSMaterialComponent.RSButtonMaterialIconDos Int_Guardar;
    private javax.swing.JTable Tabla_Documentos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private RSMaterialComponent.RSButtonMaterialIconDos lnt_Buscar;
    private extra.PanelRound panelRound4;
    private extra.PanelRound panelRound5;
    private RSMaterialComponent.RSButtonMaterialIconDos rSButtonMaterialIconDos5;
    // End of variables declaration//GEN-END:variables
}
