/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista.inventario.materias_primas;

import vista.autenticacion.Registro_DocIdentidadVista;
import controlador.inventario.materias_primas.MPControlador;
import dao.inventario.materias_primas.MPDAO;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.ZoneId;
import java.util.Date;
import modelo.inventario.materias_primas.MateriaPrima;
import java.util.List;
import javax.swing.InputVerifier;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;


import vista.proveedores.Buscar_ProveedorVista;

/**
 *
 * @author brand
 */
public class Registro_MPVista extends javax.swing.JPanel {
    
        MateriaPrima PM = new MateriaPrima();
        MPDAO MPDao = new MPDAO();
        DefaultTableModel Controlado = new DefaultTableModel();
        
    public Registro_MPVista() {
        initComponents();
        ListarPrimas();
        
        //Evita mostrar fechas pasadas y futuras solo la fecha de hoy
        Date hoy = new Date(); // fecha actual
        Pri_Fecha.setMinSelectableDate(hoy);
        Pri_Fecha.setMaxSelectableDate(hoy);
        Pri_Fecha.setDate(hoy);
        //Desactiva para modificar la fecha registro
        Pri_Fecha.setEnabled(false);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    public void ListarPrimas() {
        List<MateriaPrima> MPrimas = MPDao.ListarMateriaPrima();
        Controlado = (DefaultTableModel) Tabla_Primas.getModel();
        Object[] ob = new Object[8];
        for (int i = 0; i < MPrimas.size(); i++) {
            ob[0] = MPrimas.get(i).getIdMateriaPrima();
            ob[1] = MPrimas.get(i).getNombre();
            ob[2] = MPrimas.get(i).getDescripcion();
            ob[3] = MPrimas.get(i).getUnidadMedida();
            ob[4] = MPrimas.get(i).getStockMinimo();
            ob[5] = MPrimas.get(i).getTipoMP();
            ob[6] = MPrimas.get(i).getRutaImagen();
            ob[7] = MPrimas.get(i).getFechaSubida();
            Controlado.addRow(ob);
        }
        Tabla_Primas.setModel(Controlado);
    }
    
        public void LimpiarTable() {
        for (int i = 0; i < Controlado.getRowCount(); i++) {
            Controlado.removeRow(i);
            i = i - 1;
    }
    }
    
  
    
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        rSButtonMaterialIconDos5 = new RSMaterialComponent.RSButtonMaterialIconDos();
        rSButtonMaterialIconDos7 = new RSMaterialComponent.RSButtonMaterialIconDos();
        rSButtonMaterialIconDos8 = new RSMaterialComponent.RSButtonMaterialIconDos();
        rSButtonMaterialIconDos9 = new RSMaterialComponent.RSButtonMaterialIconDos();
        rSButtonMaterialIconDos10 = new RSMaterialComponent.RSButtonMaterialIconDos();
        rSButtonMaterialIconDos11 = new RSMaterialComponent.RSButtonMaterialIconDos();
        rSButtonMaterialIconDos12 = new RSMaterialComponent.RSButtonMaterialIconDos();
        rSButtonMaterialIconDos13 = new RSMaterialComponent.RSButtonMaterialIconDos();
        rSButtonMaterialIconDos14 = new RSMaterialComponent.RSButtonMaterialIconDos();
        rSButtonMaterialIconDos15 = new RSMaterialComponent.RSButtonMaterialIconDos();
        rSButtonMaterialIconDos16 = new RSMaterialComponent.RSButtonMaterialIconDos();
        rSButtonMaterialIconDos17 = new RSMaterialComponent.RSButtonMaterialIconDos();
        rSButtonMaterialIconDos18 = new RSMaterialComponent.RSButtonMaterialIconDos();
        rSButtonMaterialIconDos19 = new RSMaterialComponent.RSButtonMaterialIconDos();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        rSButtonMaterialIconDos2 = new RSMaterialComponent.RSButtonMaterialIconDos();
        rSButtonMaterialIconDos3 = new RSMaterialComponent.RSButtonMaterialIconDos();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        rSButtonMaterialIconDos20 = new RSMaterialComponent.RSButtonMaterialIconDos();
        panelRound1 = new extra.PanelRound();
        Pri_Codigo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Pri_Nombre = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Pri_Stock = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Pri_Descripcion = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        Pri_Fecha = new com.toedter.calendar.JDateChooser();
        Pri_Medida = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        Pri_TipoMP = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        panelRound2 = new extra.PanelRound();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        Pri_CodigoPro = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        Pri_NombrePro = new javax.swing.JTextField();
        Pri_ApellidosPro = new javax.swing.JTextField();
        rSButtonMaterialIconDos4 = new RSMaterialComponent.RSButtonMaterialIconDos();
        panelRound3 = new extra.PanelRound();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla_Primas = new javax.swing.JTable();
        Pri_Eliminar = new RSMaterialComponent.RSButtonMaterialIconDos();
        Pri_Guardar = new RSMaterialComponent.RSButtonMaterialIconDos();
        Pri_Editar = new RSMaterialComponent.RSButtonMaterialIconDos();
        Pri_Buscar = new RSMaterialComponent.RSButtonMaterialIconDos();

        jLabel1.setBackground(new java.awt.Color(58, 42, 83));
        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(38, 7, 6));
        jLabel1.setText("Registro de Productos");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(38, 7, 6));
        jLabel2.setText("Complete la informacion de los clientes");

        rSButtonMaterialIconDos5.setBackground(new java.awt.Color(38, 7, 6));
        rSButtonMaterialIconDos5.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.DASHBOARD);
        rSButtonMaterialIconDos5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMaterialIconDos5ActionPerformed(evt);
            }
        });

        rSButtonMaterialIconDos7.setBackground(new java.awt.Color(16, 16, 16));
        rSButtonMaterialIconDos7.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.FILTER_HDR);
        rSButtonMaterialIconDos7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMaterialIconDos7ActionPerformed(evt);
            }
        });

        rSButtonMaterialIconDos8.setBackground(new java.awt.Color(16, 16, 16));
        rSButtonMaterialIconDos8.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.FILTER_HDR);
        rSButtonMaterialIconDos8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMaterialIconDos8ActionPerformed(evt);
            }
        });

        rSButtonMaterialIconDos9.setBackground(new java.awt.Color(16, 16, 16));
        rSButtonMaterialIconDos9.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.FILTER_HDR);
        rSButtonMaterialIconDos9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMaterialIconDos9ActionPerformed(evt);
            }
        });

        rSButtonMaterialIconDos10.setBackground(new java.awt.Color(16, 16, 16));
        rSButtonMaterialIconDos10.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.FILTER_HDR);
        rSButtonMaterialIconDos10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMaterialIconDos10ActionPerformed(evt);
            }
        });

        rSButtonMaterialIconDos11.setBackground(new java.awt.Color(16, 16, 16));
        rSButtonMaterialIconDos11.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.FILTER_HDR);
        rSButtonMaterialIconDos11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMaterialIconDos11ActionPerformed(evt);
            }
        });

        rSButtonMaterialIconDos12.setBackground(new java.awt.Color(16, 16, 16));
        rSButtonMaterialIconDos12.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.FILTER_HDR);
        rSButtonMaterialIconDos12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMaterialIconDos12ActionPerformed(evt);
            }
        });

        rSButtonMaterialIconDos13.setBackground(new java.awt.Color(16, 16, 16));
        rSButtonMaterialIconDos13.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.FILTER_HDR);
        rSButtonMaterialIconDos13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMaterialIconDos13ActionPerformed(evt);
            }
        });

        rSButtonMaterialIconDos14.setBackground(new java.awt.Color(16, 16, 16));
        rSButtonMaterialIconDos14.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.FILTER_HDR);
        rSButtonMaterialIconDos14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMaterialIconDos14ActionPerformed(evt);
            }
        });

        rSButtonMaterialIconDos15.setBackground(new java.awt.Color(16, 16, 16));
        rSButtonMaterialIconDos15.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.FILTER_HDR);
        rSButtonMaterialIconDos15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMaterialIconDos15ActionPerformed(evt);
            }
        });

        rSButtonMaterialIconDos16.setBackground(new java.awt.Color(16, 16, 16));
        rSButtonMaterialIconDos16.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.FILTER_HDR);
        rSButtonMaterialIconDos16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMaterialIconDos16ActionPerformed(evt);
            }
        });

        rSButtonMaterialIconDos17.setBackground(new java.awt.Color(16, 16, 16));
        rSButtonMaterialIconDos17.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.FILTER_HDR);
        rSButtonMaterialIconDos17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMaterialIconDos17ActionPerformed(evt);
            }
        });

        rSButtonMaterialIconDos18.setBackground(new java.awt.Color(16, 16, 16));
        rSButtonMaterialIconDos18.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.FILTER_HDR);
        rSButtonMaterialIconDos18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMaterialIconDos18ActionPerformed(evt);
            }
        });

        rSButtonMaterialIconDos19.setBackground(new java.awt.Color(16, 16, 16));
        rSButtonMaterialIconDos19.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.FILTER_HDR);
        rSButtonMaterialIconDos19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMaterialIconDos19ActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 12, 26));
        jLabel11.setText("Datos del cliente");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 12, 26));
        jLabel12.setText("Datos del cliente");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 12, 26));
        jLabel13.setText("Datos del cliente");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 12, 26));
        jLabel14.setText("Datos del cliente");

        rSButtonMaterialIconDos2.setBackground(new java.awt.Color(136, 136, 136));

        rSButtonMaterialIconDos3.setBackground(new java.awt.Color(136, 136, 136));

        setBackground(new java.awt.Color(239, 235, 233));

        jLabel3.setBackground(new java.awt.Color(16, 16, 16));
        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(16, 16, 16));
        jLabel3.setText("Registro de Productos de materia Prima");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(38, 7, 6));
        jLabel4.setText("Complete la informacion de los producto de materia prima");

        rSButtonMaterialIconDos20.setBackground(new java.awt.Color(16, 16, 16));
        rSButtonMaterialIconDos20.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.FILTER_HDR);
        rSButtonMaterialIconDos20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMaterialIconDos20ActionPerformed(evt);
            }
        });

        panelRound1.setBackground(new java.awt.Color(255, 255, 255));
        panelRound1.setRoundBottomLeft(75);
        panelRound1.setRoundBottomRight(75);
        panelRound1.setRoundTopLeft(75);
        panelRound1.setRoundTopRight(75);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Codigo:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Nombre:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("Stock:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("Fecha Entrada:");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setText("Descripcion");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel19.setText("Medida");

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel21.setText("Tipo MP");

        javax.swing.GroupLayout panelRound1Layout = new javax.swing.GroupLayout(panelRound1);
        panelRound1.setLayout(panelRound1Layout);
        panelRound1Layout.setHorizontalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel21)
                    .addComponent(jLabel19)
                    .addComponent(jLabel10)
                    .addComponent(Pri_Descripcion)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(Pri_Stock)
                    .addComponent(jLabel6)
                    .addComponent(Pri_Nombre)
                    .addComponent(jLabel5)
                    .addComponent(Pri_Codigo)
                    .addComponent(Pri_Fecha, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
                    .addComponent(Pri_Medida)
                    .addComponent(Pri_TipoMP))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        panelRound1Layout.setVerticalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Pri_Codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Pri_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Pri_Stock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Pri_Fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Pri_Descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Pri_Medida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Pri_TipoMP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        panelRound2.setBackground(new java.awt.Color(255, 255, 255));
        panelRound2.setRoundBottomLeft(75);
        panelRound2.setRoundBottomRight(75);
        panelRound2.setRoundTopLeft(75);
        panelRound2.setRoundTopRight(75);

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 12, 26));
        jLabel15.setText("Datos del Proveedor");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel16.setText("Codigo Proveedor:");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel17.setText("Nombres:");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel18.setText("Apellidos:");

        Pri_ApellidosPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Pri_ApellidosProActionPerformed(evt);
            }
        });

        rSButtonMaterialIconDos4.setBackground(new java.awt.Color(136, 136, 136));
        rSButtonMaterialIconDos4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMaterialIconDos4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRound2Layout = new javax.swing.GroupLayout(panelRound2);
        panelRound2.setLayout(panelRound2Layout);
        panelRound2Layout.setHorizontalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addGroup(panelRound2Layout.createSequentialGroup()
                        .addGroup(panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(Pri_CodigoPro, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Pri_NombrePro, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17))
                        .addGap(18, 18, 18)
                        .addGroup(panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Pri_ApellidosPro, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(rSButtonMaterialIconDos4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );
        panelRound2Layout.setVerticalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelRound2Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18)))
                    .addComponent(rSButtonMaterialIconDos4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Pri_CodigoPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Pri_NombrePro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Pri_ApellidosPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        panelRound3.setBackground(new java.awt.Color(255, 255, 255));
        panelRound3.setRoundBottomLeft(75);
        panelRound3.setRoundBottomRight(75);
        panelRound3.setRoundTopLeft(75);
        panelRound3.setRoundTopRight(75);

        Tabla_Primas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre", "Descripcion", "Medida", "Stock", "TipoMP", "RutaImagen", "Fecha"
            }
        ));
        jScrollPane1.setViewportView(Tabla_Primas);

        javax.swing.GroupLayout panelRound3Layout = new javax.swing.GroupLayout(panelRound3);
        panelRound3.setLayout(panelRound3Layout);
        panelRound3Layout.setHorizontalGroup(
            panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 766, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        panelRound3Layout.setVerticalGroup(
            panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound3Layout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        Pri_Eliminar.setBackground(new java.awt.Color(16, 16, 16));
        Pri_Eliminar.setText("Eliminar");
        Pri_Eliminar.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.DELETE);
        Pri_Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Pri_EliminarActionPerformed(evt);
            }
        });

        Pri_Guardar.setBackground(new java.awt.Color(16, 16, 16));
        Pri_Guardar.setText("Guardar");
        Pri_Guardar.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.SAVE);
        Pri_Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Pri_GuardarActionPerformed(evt);
            }
        });

        Pri_Editar.setBackground(new java.awt.Color(16, 16, 16));
        Pri_Editar.setText("Editar");
        Pri_Editar.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.EDIT);
        Pri_Editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Pri_EditarActionPerformed(evt);
            }
        });

        Pri_Buscar.setBackground(new java.awt.Color(16, 16, 16));
        Pri_Buscar.setText("Buscar");
        Pri_Buscar.setToolTipText("");
        Pri_Buscar.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.SEARCH);
        Pri_Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Pri_BuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(panelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Pri_Eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Pri_Guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Pri_Editar, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Pri_Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(panelRound3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelRound2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rSButtonMaterialIconDos20, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rSButtonMaterialIconDos20, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelRound2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(panelRound3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Pri_Eliminar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Pri_Guardar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Pri_Editar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Pri_Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void rSButtonMaterialIconDos5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMaterialIconDos5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonMaterialIconDos5ActionPerformed

    private void rSButtonMaterialIconDos7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMaterialIconDos7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonMaterialIconDos7ActionPerformed

    private void rSButtonMaterialIconDos8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMaterialIconDos8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonMaterialIconDos8ActionPerformed

    private void rSButtonMaterialIconDos9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMaterialIconDos9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonMaterialIconDos9ActionPerformed

    private void rSButtonMaterialIconDos10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMaterialIconDos10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonMaterialIconDos10ActionPerformed

    private void rSButtonMaterialIconDos11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMaterialIconDos11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonMaterialIconDos11ActionPerformed

    private void rSButtonMaterialIconDos12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMaterialIconDos12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonMaterialIconDos12ActionPerformed

    private void rSButtonMaterialIconDos13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMaterialIconDos13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonMaterialIconDos13ActionPerformed

    private void rSButtonMaterialIconDos14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMaterialIconDos14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonMaterialIconDos14ActionPerformed

    private void rSButtonMaterialIconDos15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMaterialIconDos15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonMaterialIconDos15ActionPerformed

    private void rSButtonMaterialIconDos16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMaterialIconDos16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonMaterialIconDos16ActionPerformed

    private void rSButtonMaterialIconDos17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMaterialIconDos17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonMaterialIconDos17ActionPerformed

    private void rSButtonMaterialIconDos18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMaterialIconDos18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonMaterialIconDos18ActionPerformed

    private void rSButtonMaterialIconDos19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMaterialIconDos19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonMaterialIconDos19ActionPerformed

    private void rSButtonMaterialIconDos20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMaterialIconDos20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonMaterialIconDos20ActionPerformed

    private void Pri_ApellidosProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Pri_ApellidosProActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Pri_ApellidosProActionPerformed

    private void Pri_EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Pri_EliminarActionPerformed
        // Verifica si hay un cliente seleccionado
        int fila = Tabla_Primas.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(null, "⚠️ Debes seleccionar un dato de la tabla para eliminar.");
            return;
        }

        // Confirmación con el usuario antes de eliminar
        int confirmacion = JOptionPane.showConfirmDialog(null,
                "¿Estás seguro de que deseas eliminar este dato?",
                "Confirmar eliminación", JOptionPane.YES_NO_OPTION);
        if (confirmacion != JOptionPane.YES_OPTION) {
            return;
        }

        try {
            // Obtiene el ID del cliente seleccionado
            String idPM = Tabla_Primas.getValueAt(fila, 0).toString();

            // Llama al controlador (no al DAO directamente)
            MPControlador controlador = new MPControlador();
            boolean eliminado = controlador.eliminarPrima(idPM);

            if (eliminado) {
                JOptionPane.showMessageDialog(null, "✅ Cliente eliminado correctamente.");
                LimpiarPrimas();
                LimpiarTable();
                ListarPrimas();
            } else {
                JOptionPane.showMessageDialog(null, "❌ No se pudo eliminar el cliente. Verifica si tiene relaciones con otros datos.");
            }

        } catch (Exception e) {
            // Manejo de errores para usuarios finales
            String mensaje = e.getMessage().toLowerCase();
            if (mensaje.contains("foreign key")) {
                JOptionPane.showMessageDialog(null, "⚠️ Este cliente está relacionado con otros datos. No se puede eliminar.");
            } else if (mensaje.contains("too long")) {
                JOptionPane.showMessageDialog(null, "⚠️ Uno de los campos excede el límite permitido.");
            } else {
                JOptionPane.showMessageDialog(null, "❌ Error inesperado al eliminar el cliente. Intenta nuevamente.");
            }
            e.printStackTrace(); // Para el programador
        }
    }//GEN-LAST:event_Pri_EliminarActionPerformed

    private void Pri_GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Pri_GuardarActionPerformed
        // Instanciamos con cliente
        MateriaPrima MP = new MateriaPrima();

        // Setear con los datos de los JTextField
        MP.setIdMateriaPrima(Pri_Codigo.getText());
        MP.setNombre(Pri_Nombre.getText());
        MP.setStockMinimo(Integer.parseInt(Pri_Stock.getText()));
        MP.setDescripcion(Pri_Descripcion.getText());
        MP.setUnidadMedida(Pri_Medida.getText());
        MP.setTipoMP(Pri_TipoMP.getText());
        
        // Para agregar los datos del JDateChooser
        Date fechaSeleccionada = Pri_Fecha.getDate();
        if (fechaSeleccionada == null) {
            JOptionPane.showMessageDialog(null, "Selecciona una fecha de registro.");
            return;
        }

        // Convertimos a LocalDateTime
        LocalDateTime fechaRegistro = fechaSeleccionada.toInstant()
                .atZone(ZoneId.systemDefault())
                .toLocalDateTime();

        // ✅ Validar solo la fecha (sin considerar la hora)
        if (fechaRegistro.toLocalDate().isBefore(LocalDate.now())) {
            JOptionPane.showMessageDialog(null, "No se permite una fecha de registro anterior a hoy.");
            return;
        }

        MP.setFechaSubida(fechaRegistro);

        // Registrar cliente
        MPControlador controlador = new MPControlador();
        controlador.registrarPrimas(MP);
        
        // Actualizar la tabla después de guardar 
        LimpiarPrimas();
        LimpiarTable();
        ListarPrimas();
    }//GEN-LAST:event_Pri_GuardarActionPerformed

    private void Pri_EditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Pri_EditarActionPerformed
        // TODO add your handling code here:
        int fila = Tabla_Primas.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(null, "⚠️ Debes seleccionar una Materia Prima de la tabla para modificar.");
            return;
        }

        // Confirmación antes de modificar
        int confirmacion = JOptionPane.showConfirmDialog(null,
                "¿Estás seguro de que deseas modificar esta Materia Prima?",
                "Confirmar modificación", JOptionPane.YES_NO_OPTION);
        if (confirmacion != JOptionPane.YES_OPTION) {
            return;
        }

        try {
            // Se instancia un nuevo objeto Cliente con los datos actuales del formulario
            MateriaPrima MP = new MateriaPrima();
            MP.setIdMateriaPrima(Tabla_Primas.getValueAt(fila, 0).toString()); // ID viene de la tabla (no se edita)
            MP.setNombre(Pri_Nombre.getText().trim());
            MP.setStockMinimo(Integer.parseInt(Pri_Stock.getText().trim()));
            MP.setDescripcion(Pri_Descripcion.getText().trim());
            MP.setUnidadMedida(Pri_Medida.getText().trim());
            MP.setTipoMP(Pri_TipoMP.getText().trim());

            // Se recupera la fecha original desde la tabla
            MP.setFechaSubida(LocalDateTime.now());

            // Validación: campos obligatorios
            if (MP.getNombre().isEmpty() || MP.getStockMinimo()==0) {
                JOptionPane.showMessageDialog(null, "⚠️ El Nombre y Stock no pueden estar vacíos.");
                return;
            }

            // Validación: solo letras en nombre y apellido
            if (!MP.getNombre().matches("[a-zA-ZáéíóúÁÉÍÓÚñÑ ]+")) {
                JOptionPane.showMessageDialog(null, "⚠️ El nombre y apellido deben contener solo letras.");
                return;
            }

            // Validación: límite de caracteres
            if (MP.getNombre().length() > 50) {
                JOptionPane.showMessageDialog(null, "⚠️ El nombre exceden el límite de 50 caracteres.");
                return;
            }

            // Llamada al controlador para aplicar la modificación
            MPControlador controlador = new MPControlador();
            boolean modificado = controlador.ModificarPrima(MP);

            if (modificado) {
                JOptionPane.showMessageDialog(null, "✅ Materia Prima modificado correctamente.");
                LimpiarPrimas();
                LimpiarTable();
                ListarPrimas();
            } else {
                JOptionPane.showMessageDialog(null, "❌ No se pudo modificar la Materia Prima.");
            }

        } catch (Exception e) {
            // Mensaje amigable para cualquier error inesperado
            String msg = e.getMessage().toLowerCase();
            if (msg.contains("too long")) {
                JOptionPane.showMessageDialog(null, "⚠️ Uno de los campos excede el límite permitido.");
            } else {
                JOptionPane.showMessageDialog(null, "❌ Ocurrió un error al modificar la Materia Prima. Verifica los datos ingresados.");
            }
            e.printStackTrace(); // Registro técnico para desarrolladores
        }
    }//GEN-LAST:event_Pri_EditarActionPerformed

    private void Pri_BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Pri_BuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Pri_BuscarActionPerformed

    private void rSButtonMaterialIconDos4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMaterialIconDos4ActionPerformed
        Buscar_ProveedorVista BusProv = new Buscar_ProveedorVista();
        BusProv.setVisible(true);
    }//GEN-LAST:event_rSButtonMaterialIconDos4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Pri_ApellidosPro;
    private RSMaterialComponent.RSButtonMaterialIconDos Pri_Buscar;
    private javax.swing.JTextField Pri_Codigo;
    private javax.swing.JTextField Pri_CodigoPro;
    private javax.swing.JTextField Pri_Descripcion;
    private RSMaterialComponent.RSButtonMaterialIconDos Pri_Editar;
    private RSMaterialComponent.RSButtonMaterialIconDos Pri_Eliminar;
    private com.toedter.calendar.JDateChooser Pri_Fecha;
    private RSMaterialComponent.RSButtonMaterialIconDos Pri_Guardar;
    private javax.swing.JTextField Pri_Medida;
    private javax.swing.JTextField Pri_Nombre;
    private javax.swing.JTextField Pri_NombrePro;
    private javax.swing.JTextField Pri_Stock;
    private javax.swing.JTextField Pri_TipoMP;
    private javax.swing.JTable Tabla_Primas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private extra.PanelRound panelRound1;
    private extra.PanelRound panelRound2;
    private extra.PanelRound panelRound3;
    private RSMaterialComponent.RSButtonMaterialIconDos rSButtonMaterialIconDos10;
    private RSMaterialComponent.RSButtonMaterialIconDos rSButtonMaterialIconDos11;
    private RSMaterialComponent.RSButtonMaterialIconDos rSButtonMaterialIconDos12;
    private RSMaterialComponent.RSButtonMaterialIconDos rSButtonMaterialIconDos13;
    private RSMaterialComponent.RSButtonMaterialIconDos rSButtonMaterialIconDos14;
    private RSMaterialComponent.RSButtonMaterialIconDos rSButtonMaterialIconDos15;
    private RSMaterialComponent.RSButtonMaterialIconDos rSButtonMaterialIconDos16;
    private RSMaterialComponent.RSButtonMaterialIconDos rSButtonMaterialIconDos17;
    private RSMaterialComponent.RSButtonMaterialIconDos rSButtonMaterialIconDos18;
    private RSMaterialComponent.RSButtonMaterialIconDos rSButtonMaterialIconDos19;
    private RSMaterialComponent.RSButtonMaterialIconDos rSButtonMaterialIconDos2;
    private RSMaterialComponent.RSButtonMaterialIconDos rSButtonMaterialIconDos20;
    private RSMaterialComponent.RSButtonMaterialIconDos rSButtonMaterialIconDos3;
    private RSMaterialComponent.RSButtonMaterialIconDos rSButtonMaterialIconDos4;
    private RSMaterialComponent.RSButtonMaterialIconDos rSButtonMaterialIconDos5;
    private RSMaterialComponent.RSButtonMaterialIconDos rSButtonMaterialIconDos7;
    private RSMaterialComponent.RSButtonMaterialIconDos rSButtonMaterialIconDos8;
    private RSMaterialComponent.RSButtonMaterialIconDos rSButtonMaterialIconDos9;
    // End of variables declaration//GEN-END:variables
    private void LimpiarPrimas() {
        Pri_Codigo.setText("");
        Pri_Nombre.setText("");
        Pri_Stock.setText("");
        Pri_Descripcion.setText("");
        Pri_Medida.setText("");
        Pri_TipoMP.setText("");
    }
}
