/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista.inventario.materias_primas;

import vista.proveedores.Buscar_ProveedorVista;

/**
 *
 * @author brand
 */
public class Registro_MPVista extends javax.swing.JPanel {

    /**
     * Creates new form Primas
     */
    public Registro_MPVista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        rSButtonMaterialIconDos5 = new RSMaterialComponent.RSButtonMaterialIconDos();
        rSButtonMaterialIconDos7 = new RSMaterialComponent.RSButtonMaterialIconDos();
        rSButtonMaterialIconDos8 = new RSMaterialComponent.RSButtonMaterialIconDos();
        rSButtonMaterialIconDos9 = new RSMaterialComponent.RSButtonMaterialIconDos();
        rSButtonMaterialIconDos10 = new RSMaterialComponent.RSButtonMaterialIconDos();
        rSButtonMaterialIconDos11 = new RSMaterialComponent.RSButtonMaterialIconDos();
        rSButtonMaterialIconDos12 = new RSMaterialComponent.RSButtonMaterialIconDos();
        rSButtonMaterialIconDos13 = new RSMaterialComponent.RSButtonMaterialIconDos();
        rSButtonMaterialIconDos14 = new RSMaterialComponent.RSButtonMaterialIconDos();
        rSButtonMaterialIconDos15 = new RSMaterialComponent.RSButtonMaterialIconDos();
        rSButtonMaterialIconDos16 = new RSMaterialComponent.RSButtonMaterialIconDos();
        rSButtonMaterialIconDos17 = new RSMaterialComponent.RSButtonMaterialIconDos();
        rSButtonMaterialIconDos18 = new RSMaterialComponent.RSButtonMaterialIconDos();
        rSButtonMaterialIconDos19 = new RSMaterialComponent.RSButtonMaterialIconDos();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        rSButtonMaterialIconDos2 = new RSMaterialComponent.RSButtonMaterialIconDos();
        rSButtonMaterialIconDos3 = new RSMaterialComponent.RSButtonMaterialIconDos();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        rSButtonMaterialIconDos20 = new RSMaterialComponent.RSButtonMaterialIconDos();
        panelRound1 = new extra.PanelRound();
        Pri_Codigo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Pri_Nombre = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Pri_Stock = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Pri_PrecioUnitario = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        Pri_TotalPagar = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        panelRound2 = new extra.PanelRound();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        Pri_CodigoPro = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        Pri_NombrePro = new javax.swing.JTextField();
        Pri_ApellidosPro = new javax.swing.JTextField();
        rSButtonMaterialIconDos4 = new RSMaterialComponent.RSButtonMaterialIconDos();
        panelRound3 = new extra.PanelRound();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla_Primas = new javax.swing.JTable();
        Pri_Eliminar = new RSMaterialComponent.RSButtonMaterialIconDos();
        Pri_Guardar = new RSMaterialComponent.RSButtonMaterialIconDos();
        Pri_Editar = new RSMaterialComponent.RSButtonMaterialIconDos();
        Pri_Buscar = new RSMaterialComponent.RSButtonMaterialIconDos();

        jLabel1.setBackground(new java.awt.Color(58, 42, 83));
        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(38, 7, 6));
        jLabel1.setText("Registro de Productos");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(38, 7, 6));
        jLabel2.setText("Complete la informacion de los clientes");

        rSButtonMaterialIconDos5.setBackground(new java.awt.Color(38, 7, 6));
        rSButtonMaterialIconDos5.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.DASHBOARD);
        rSButtonMaterialIconDos5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMaterialIconDos5ActionPerformed(evt);
            }
        });

        rSButtonMaterialIconDos7.setBackground(new java.awt.Color(16, 16, 16));
        rSButtonMaterialIconDos7.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.FILTER_HDR);
        rSButtonMaterialIconDos7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMaterialIconDos7ActionPerformed(evt);
            }
        });

        rSButtonMaterialIconDos8.setBackground(new java.awt.Color(16, 16, 16));
        rSButtonMaterialIconDos8.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.FILTER_HDR);
        rSButtonMaterialIconDos8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMaterialIconDos8ActionPerformed(evt);
            }
        });

        rSButtonMaterialIconDos9.setBackground(new java.awt.Color(16, 16, 16));
        rSButtonMaterialIconDos9.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.FILTER_HDR);
        rSButtonMaterialIconDos9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMaterialIconDos9ActionPerformed(evt);
            }
        });

        rSButtonMaterialIconDos10.setBackground(new java.awt.Color(16, 16, 16));
        rSButtonMaterialIconDos10.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.FILTER_HDR);
        rSButtonMaterialIconDos10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMaterialIconDos10ActionPerformed(evt);
            }
        });

        rSButtonMaterialIconDos11.setBackground(new java.awt.Color(16, 16, 16));
        rSButtonMaterialIconDos11.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.FILTER_HDR);
        rSButtonMaterialIconDos11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMaterialIconDos11ActionPerformed(evt);
            }
        });

        rSButtonMaterialIconDos12.setBackground(new java.awt.Color(16, 16, 16));
        rSButtonMaterialIconDos12.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.FILTER_HDR);
        rSButtonMaterialIconDos12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMaterialIconDos12ActionPerformed(evt);
            }
        });

        rSButtonMaterialIconDos13.setBackground(new java.awt.Color(16, 16, 16));
        rSButtonMaterialIconDos13.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.FILTER_HDR);
        rSButtonMaterialIconDos13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMaterialIconDos13ActionPerformed(evt);
            }
        });

        rSButtonMaterialIconDos14.setBackground(new java.awt.Color(16, 16, 16));
        rSButtonMaterialIconDos14.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.FILTER_HDR);
        rSButtonMaterialIconDos14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMaterialIconDos14ActionPerformed(evt);
            }
        });

        rSButtonMaterialIconDos15.setBackground(new java.awt.Color(16, 16, 16));
        rSButtonMaterialIconDos15.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.FILTER_HDR);
        rSButtonMaterialIconDos15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMaterialIconDos15ActionPerformed(evt);
            }
        });

        rSButtonMaterialIconDos16.setBackground(new java.awt.Color(16, 16, 16));
        rSButtonMaterialIconDos16.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.FILTER_HDR);
        rSButtonMaterialIconDos16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMaterialIconDos16ActionPerformed(evt);
            }
        });

        rSButtonMaterialIconDos17.setBackground(new java.awt.Color(16, 16, 16));
        rSButtonMaterialIconDos17.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.FILTER_HDR);
        rSButtonMaterialIconDos17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMaterialIconDos17ActionPerformed(evt);
            }
        });

        rSButtonMaterialIconDos18.setBackground(new java.awt.Color(16, 16, 16));
        rSButtonMaterialIconDos18.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.FILTER_HDR);
        rSButtonMaterialIconDos18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMaterialIconDos18ActionPerformed(evt);
            }
        });

        rSButtonMaterialIconDos19.setBackground(new java.awt.Color(16, 16, 16));
        rSButtonMaterialIconDos19.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.FILTER_HDR);
        rSButtonMaterialIconDos19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMaterialIconDos19ActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 12, 26));
        jLabel11.setText("Datos del cliente");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 12, 26));
        jLabel12.setText("Datos del cliente");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 12, 26));
        jLabel13.setText("Datos del cliente");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 12, 26));
        jLabel14.setText("Datos del cliente");

        rSButtonMaterialIconDos2.setBackground(new java.awt.Color(136, 136, 136));

        rSButtonMaterialIconDos3.setBackground(new java.awt.Color(136, 136, 136));

        setBackground(new java.awt.Color(239, 235, 233));

        jLabel3.setBackground(new java.awt.Color(16, 16, 16));
        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(16, 16, 16));
        jLabel3.setText("Registro de Productos de materia Prima");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(38, 7, 6));
        jLabel4.setText("Complete la informacion de los producto de materia prima");

        rSButtonMaterialIconDos20.setBackground(new java.awt.Color(16, 16, 16));
        rSButtonMaterialIconDos20.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.FILTER_HDR);
        rSButtonMaterialIconDos20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMaterialIconDos20ActionPerformed(evt);
            }
        });

        panelRound1.setBackground(new java.awt.Color(255, 255, 255));
        panelRound1.setRoundBottomLeft(75);
        panelRound1.setRoundBottomRight(75);
        panelRound1.setRoundTopLeft(75);
        panelRound1.setRoundTopRight(75);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Codigo:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Nombre:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("Stock:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("Fecha Entrada:");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setText("Precio Unitario:");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setText("Total Compra:");

        javax.swing.GroupLayout panelRound1Layout = new javax.swing.GroupLayout(panelRound1);
        panelRound1.setLayout(panelRound1Layout);
        panelRound1Layout.setHorizontalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel10)
                    .addComponent(Pri_TotalPagar)
                    .addComponent(jLabel9)
                    .addComponent(Pri_PrecioUnitario)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(Pri_Stock)
                    .addComponent(jLabel6)
                    .addComponent(Pri_Nombre)
                    .addComponent(jLabel5)
                    .addComponent(Pri_Codigo)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        panelRound1Layout.setVerticalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Pri_Codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Pri_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Pri_Stock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Pri_PrecioUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Pri_TotalPagar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        panelRound2.setBackground(new java.awt.Color(255, 255, 255));
        panelRound2.setRoundBottomLeft(75);
        panelRound2.setRoundBottomRight(75);
        panelRound2.setRoundTopLeft(75);
        panelRound2.setRoundTopRight(75);

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 12, 26));
        jLabel15.setText("Datos del Proveedor");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel16.setText("Codigo Proveedor:");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel17.setText("Nombres:");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel18.setText("Apellidos:");

        Pri_ApellidosPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Pri_ApellidosProActionPerformed(evt);
            }
        });

        rSButtonMaterialIconDos4.setBackground(new java.awt.Color(136, 136, 136));
        rSButtonMaterialIconDos4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMaterialIconDos4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRound2Layout = new javax.swing.GroupLayout(panelRound2);
        panelRound2.setLayout(panelRound2Layout);
        panelRound2Layout.setHorizontalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addGroup(panelRound2Layout.createSequentialGroup()
                        .addGroup(panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(Pri_CodigoPro, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Pri_NombrePro, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17))
                        .addGap(18, 18, 18)
                        .addGroup(panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Pri_ApellidosPro, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(rSButtonMaterialIconDos4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );
        panelRound2Layout.setVerticalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelRound2Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18)))
                    .addComponent(rSButtonMaterialIconDos4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Pri_CodigoPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Pri_NombrePro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Pri_ApellidosPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        panelRound3.setBackground(new java.awt.Color(255, 255, 255));
        panelRound3.setRoundBottomLeft(75);
        panelRound3.setRoundBottomRight(75);
        panelRound3.setRoundTopLeft(75);
        panelRound3.setRoundTopRight(75);

        Tabla_Primas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Producto", "Stock", "Fecha Entrada", "Precio Unitario", "Total Compra", "Codigo Pro", "Nombres", "Apellidos"
            }
        ));
        jScrollPane1.setViewportView(Tabla_Primas);

        javax.swing.GroupLayout panelRound3Layout = new javax.swing.GroupLayout(panelRound3);
        panelRound3.setLayout(panelRound3Layout);
        panelRound3Layout.setHorizontalGroup(
            panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound3Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 751, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelRound3Layout.setVerticalGroup(
            panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound3Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        Pri_Eliminar.setBackground(new java.awt.Color(16, 16, 16));
        Pri_Eliminar.setText("Eliminar");
        Pri_Eliminar.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.DELETE);
        Pri_Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Pri_EliminarActionPerformed(evt);
            }
        });

        Pri_Guardar.setBackground(new java.awt.Color(16, 16, 16));
        Pri_Guardar.setText("Guardar");
        Pri_Guardar.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.SAVE);
        Pri_Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Pri_GuardarActionPerformed(evt);
            }
        });

        Pri_Editar.setBackground(new java.awt.Color(16, 16, 16));
        Pri_Editar.setText("Editar");
        Pri_Editar.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.EDIT);
        Pri_Editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Pri_EditarActionPerformed(evt);
            }
        });

        Pri_Buscar.setBackground(new java.awt.Color(16, 16, 16));
        Pri_Buscar.setText("Buscar");
        Pri_Buscar.setToolTipText("");
        Pri_Buscar.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.SEARCH);
        Pri_Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Pri_BuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(panelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Pri_Eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Pri_Guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Pri_Editar, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Pri_Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(panelRound3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelRound2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rSButtonMaterialIconDos20, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rSButtonMaterialIconDos20, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelRound2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(panelRound3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Pri_Eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Pri_Guardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Pri_Editar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Pri_Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void rSButtonMaterialIconDos5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMaterialIconDos5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonMaterialIconDos5ActionPerformed

    private void rSButtonMaterialIconDos7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMaterialIconDos7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonMaterialIconDos7ActionPerformed

    private void rSButtonMaterialIconDos8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMaterialIconDos8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonMaterialIconDos8ActionPerformed

    private void rSButtonMaterialIconDos9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMaterialIconDos9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonMaterialIconDos9ActionPerformed

    private void rSButtonMaterialIconDos10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMaterialIconDos10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonMaterialIconDos10ActionPerformed

    private void rSButtonMaterialIconDos11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMaterialIconDos11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonMaterialIconDos11ActionPerformed

    private void rSButtonMaterialIconDos12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMaterialIconDos12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonMaterialIconDos12ActionPerformed

    private void rSButtonMaterialIconDos13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMaterialIconDos13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonMaterialIconDos13ActionPerformed

    private void rSButtonMaterialIconDos14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMaterialIconDos14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonMaterialIconDos14ActionPerformed

    private void rSButtonMaterialIconDos15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMaterialIconDos15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonMaterialIconDos15ActionPerformed

    private void rSButtonMaterialIconDos16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMaterialIconDos16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonMaterialIconDos16ActionPerformed

    private void rSButtonMaterialIconDos17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMaterialIconDos17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonMaterialIconDos17ActionPerformed

    private void rSButtonMaterialIconDos18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMaterialIconDos18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonMaterialIconDos18ActionPerformed

    private void rSButtonMaterialIconDos19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMaterialIconDos19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonMaterialIconDos19ActionPerformed

    private void rSButtonMaterialIconDos20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMaterialIconDos20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonMaterialIconDos20ActionPerformed

    private void Pri_ApellidosProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Pri_ApellidosProActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Pri_ApellidosProActionPerformed

    private void Pri_EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Pri_EliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Pri_EliminarActionPerformed

    private void Pri_GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Pri_GuardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Pri_GuardarActionPerformed

    private void Pri_EditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Pri_EditarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Pri_EditarActionPerformed

    private void Pri_BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Pri_BuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Pri_BuscarActionPerformed

    private void rSButtonMaterialIconDos4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMaterialIconDos4ActionPerformed
        Buscar_ProveedorVista BusProv = new Buscar_ProveedorVista();
        BusProv.setVisible(true);
    }//GEN-LAST:event_rSButtonMaterialIconDos4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Pri_ApellidosPro;
    private RSMaterialComponent.RSButtonMaterialIconDos Pri_Buscar;
    private javax.swing.JTextField Pri_Codigo;
    private javax.swing.JTextField Pri_CodigoPro;
    private RSMaterialComponent.RSButtonMaterialIconDos Pri_Editar;
    private RSMaterialComponent.RSButtonMaterialIconDos Pri_Eliminar;
    private RSMaterialComponent.RSButtonMaterialIconDos Pri_Guardar;
    private javax.swing.JTextField Pri_Nombre;
    private javax.swing.JTextField Pri_NombrePro;
    private javax.swing.JTextField Pri_PrecioUnitario;
    private javax.swing.JTextField Pri_Stock;
    private javax.swing.JTextField Pri_TotalPagar;
    private javax.swing.JTable Tabla_Primas;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private extra.PanelRound panelRound1;
    private extra.PanelRound panelRound2;
    private extra.PanelRound panelRound3;
    private RSMaterialComponent.RSButtonMaterialIconDos rSButtonMaterialIconDos10;
    private RSMaterialComponent.RSButtonMaterialIconDos rSButtonMaterialIconDos11;
    private RSMaterialComponent.RSButtonMaterialIconDos rSButtonMaterialIconDos12;
    private RSMaterialComponent.RSButtonMaterialIconDos rSButtonMaterialIconDos13;
    private RSMaterialComponent.RSButtonMaterialIconDos rSButtonMaterialIconDos14;
    private RSMaterialComponent.RSButtonMaterialIconDos rSButtonMaterialIconDos15;
    private RSMaterialComponent.RSButtonMaterialIconDos rSButtonMaterialIconDos16;
    private RSMaterialComponent.RSButtonMaterialIconDos rSButtonMaterialIconDos17;
    private RSMaterialComponent.RSButtonMaterialIconDos rSButtonMaterialIconDos18;
    private RSMaterialComponent.RSButtonMaterialIconDos rSButtonMaterialIconDos19;
    private RSMaterialComponent.RSButtonMaterialIconDos rSButtonMaterialIconDos2;
    private RSMaterialComponent.RSButtonMaterialIconDos rSButtonMaterialIconDos20;
    private RSMaterialComponent.RSButtonMaterialIconDos rSButtonMaterialIconDos3;
    private RSMaterialComponent.RSButtonMaterialIconDos rSButtonMaterialIconDos4;
    private RSMaterialComponent.RSButtonMaterialIconDos rSButtonMaterialIconDos5;
    private RSMaterialComponent.RSButtonMaterialIconDos rSButtonMaterialIconDos7;
    private RSMaterialComponent.RSButtonMaterialIconDos rSButtonMaterialIconDos8;
    private RSMaterialComponent.RSButtonMaterialIconDos rSButtonMaterialIconDos9;
    // End of variables declaration//GEN-END:variables
}
